SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

USE peach;

CREATE TABLE role (  
role_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,  
role_name VARCHAR(50) NOT NULL,  
PRIMARY KEY (role_id)  
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4; 

CREATE TABLE film_language_translation ( 
translation_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, 
film_id SMALLINT UNSIGNED NOT NULL, 
language_id TINYINT UNSIGNED NOT NULL, 
PRIMARY KEY (translation_id), 
KEY idx_language (language_id), 
KEY idx_film (film_id), 
CONSTRAINT fk_translation_language_id FOREIGN KEY (language_id) REFERENCES language (language_id) ON DELETE RESTRICT ON UPDATE CASCADE, 
CONSTRAINT fk_translation_film_id FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE RESTRICT ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 

CREATE TABLE film_language_subtitle ( 
subtitle_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT, 
film_id SMALLINT UNSIGNED NOT NULL, 
language_id TINYINT UNSIGNED NOT NULL, 
PRIMARY KEY (subtitle_id), 
KEY idx_language (language_id), 
KEY idx_film (film_id), 
CONSTRAINT fk__subtitle_language_id FOREIGN KEY (language_id) REFERENCES language (language_id) ON DELETE RESTRICT ON UPDATE CASCADE, 
CONSTRAINT fk_subtitle_film_id FOREIGN KEY (film_id) REFERENCES film (film_id) ON DELETE RESTRICT ON UPDATE CASCADE 
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4; 


ALTER TABLE customer ADD COLUMN age SMALLINT UNSIGNED DEFAULT NULL;


CREATE TABLE IF NOT EXISTS director ( 
id_director INT AUTO_INCREMENT PRIMARY KEY, 
nom VARCHAR(100) NOT NULL, 
prenom VARCHAR(100) NOT NULL, 
date_naissance DATE, 
nationalite VARCHAR(50));  


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


